version: '3.3'

services:
  nginx:
    build: ./dockerfiles/nginx/.
    env_file:
      - .env
    volumes:
      - ./src:/var/www/html
      - log:/var/log/nginx
    ports:
      - ${NGINX_PORT}:80
    depends_on:
      - php-fpm
      - db
    restart: always
    networks:
      - docker-laravel

  php-fpm:
    build: ./dockerfiles/php/.
    volumes:
      - ./src:/var/www/html
      - log:/var/log
    environment:
      DB_HOST: db
      DB_DATABASE: homestead
      DB_USERNAME: homestead
      DB_PASSWORD: ${MYSQL_PASSWORD}
    depends_on:
      - db
    restart: always
    networks:
      - docker-laravel

  db:
    image: mysql
    env_file:
      - .env
    environment:
      MYSQL_DATABASE: homestead
      MYSQL_USER: homestead
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
      - log:/var/log/mysql
    ports:
      - ${MYSQL_PORT}:3306
    restart: always
    networks:
      - docker-laravel

  composer:
    image: composer
    volumes:
      - ./src:/app
    networks:
      - docker-laravel
    entrypoint: composer

  npm:
    build: ./dockerfiles/nodejs/.
    volumes:
      - ./src:/var/www/html
      - log:/root/.npm/_logs
    networks:
      - docker-laravel
    entrypoint: npm

volumes:
  db_data:
  log:

networks:
  docker-laravel:
    driver: 'bridge'
