version: '3.4'

services:
  nginx:
    build: ./dockerfiles/nginx/.
    env_file:
      - .env
    volumes:
      - ./src:/var/www/html
      - ./log/nginx:/var/log/nginx
    ports:
      - ${NGINX_PORT}:80
    depends_on:
      - php-fpm
      - db
    restart: always

  php-fpm:
    build: ./dockerfiles/php/.
    volumes:
      - ./src:/var/www/html
      - ./log/cron:/var/log/cron
      - ./log/supervisor:/var/log/supervisor
      - ./log/laravel:/var/www/html/storage/logs
    environment:
      DB_HOST: db
      DB_DATABASE: homestead
      DB_USERNAME: homestead
      DB_PASSWORD: ${MYSQL_PASSWORD}
    depends_on:
      - db
    restart: always

  db:
    image: mysql
    env_file:
      - .env
    environment:
      MYSQL_DATABASE: homestead
      MYSQL_USER: homestead
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    command: ["--default-authentication-plugin=mysql_native_password"]
    entrypoint: ['/entrypoint.sh', '--character-set-server=utf8', '--collation-server=utf8_general_ci']
    healthcheck:
      test: "/usr/bin/mysql --user=homestead --password=${MYSQL_PASSWORD} --execute \"SHOW DATABASES;\""
      interval: 3s
      timeout: 2s
      retries: 5
    volumes:
      - ./db_data:/var/lib/mysql
      - ./log/mysql:/var/log/mysql
    ports:
      - ${MYSQL_PORT}:3306
    restart: always

  composer:
    image: composer
    volumes:
      - ./src:/app
    entrypoint: composer

  npm:
    build: ./dockerfiles/nodejs/.
    volumes:
      - ./src:/var/www/html
      - ./log/npm:/root/.npm/_logs
    entrypoint: npm
