version: "3.8"

services:
  nginx:
    build: ./dockerfiles/nginx/.
    env_file:
      - .env
    volumes:
      - ./src:/var/www/html
      - ./log/nginx:/var/log/nginx
    ports:
      - ${NGINX_PORT}:80
    depends_on:
      - php-fpm
      - database
    restart: unless-stopped

  php-fpm:
    build: ./dockerfiles/php/.
    volumes:
      - ./src:/var/www/html
      - ./log/cron:/var/log/cron
      - ./log/supervisor:/var/log/supervisor
      - ./log/laravel:/var/www/html/storage/logs
    environment:
      DB_HOST: database
      DB_DATABASE: laravel
      DB_USERNAME: laravel
      DB_PASSWORD: ${MYSQL_PASSWORD}
    depends_on:
      - database
    restart: unless-stopped

  database:
    image: mysql
    env_file:
      - .env
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    command: ["--default-authentication-plugin=mysql_native_password"]
    entrypoint: ["/entrypoint.sh", "--character-set-server=utf8", "--collation-server=utf8_general_ci"]
    healthcheck:
      test: "/usr/bin/mysql --user=${MYSQL_USER} --password=${MYSQL_PASSWORD} --execute \"SHOW DATABASES;\""
      interval: 3s
      timeout: 2s
      retries: 5
    volumes:
      - ./db_data:/var/lib/mysql
      - ./log/mysql:/var/log/mysql
    ports:
      - ${MYSQL_PORT}:3306
    restart: unless-stopped

  composer:
    image: composer
    user: 1000:1000
    volumes:
      - ./src:/app

  npm:
    build: ./dockerfiles/nodejs/.
    user: 1000:1000
    working_dir: /app
    volumes:
      - ./src:/app
      - ./log/npm:/root/.npm/_logs
    entrypoint: npm
