version: '3.1'

services:
  nginx:
    image: nginx
    working_dir: /var/www/html
    ports:
      - 8080:80
      - 8443:443
    volumes:
      - ./project:/var/www/html
      - ./dockerfiles/nginx/vhost.conf:/etc/nginx/conf.d/default.conf
      - log:/var/log/nginx
    links:
      - php-72-fpm
    depends_on:
      - php-72-fpm
      - mysql
    restart: always
    networks:
      - laravel-docker-network

  php-72-fpm:
    build: ./dockerfiles/php/.
    working_dir: /var/www/html
    volumes:
      - ./project:/var/www/html
      - log:/var/log
    environment:
      - DB_HOST=mysql
      - DB_DATABASE=homestead
      - DB_USERNAME=homestead
      - DB_PASSWORD=QLcnbtchbhV2pi2ZY0IY
    links:
      - mysql
    depends_on:
      - mysql
    restart: always
    networks:
      - laravel-docker-network

  mysql:
    image: mysql
    ports:
      - 33061:3306
    volumes:
      - db-data:/var/lib/mysql
      - log:/var/log/mysql
    environment:
      - MYSQL_DATABASE=homestead
      - MYSQL_ROOT_PASSWORD=dQDDEm4eSSuCZmiOcYmF
      - MYSQL_USER=homestead
      - MYSQL_PASSWORD=QLcnbtchbhV2pi2ZY0IY
    restart: always
    networks:
      - laravel-docker-network

  composer:
    image: composer
    working_dir: /var/www/html
    entrypoint: composer
    volumes:
      - ./project:/var/www/html
    networks:
      - laravel-docker-network

  npm:
    build: ./dockerfiles/nodejs/.
    working_dir: /var/www/html
    entrypoint: npm
    volumes:
      - ./project:/var/www/html
      - log:/root/.npm/_logs/
    networks:
      - laravel-docker-network

volumes:
  db-data:
  log:

networks:
  laravel-docker-network:
    driver: 'bridge'
